### ISSUE TITLE
Change year in footer from 2020 to 2021

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/blogbook#1]
This is the first basic issue for beginners.
Files to lookout
* includes/footer.php

**Comment by ayush20021** [comment]
I will do it

**Comment by chaitak-gorai** [comment]
> I will do it

Ok, go for it

**Comment by chaitak-gorai** [comment]
This issue is solved by the commit 4416d2e20525d0cb14272bbeb98766c60a4d73e2
Speacial thanks to @katkava for the contribution.
