### ISSUE TITLE
Create a profile page template for users

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/blogbook#10]
We presently don't have a profile page for authors.

Create a template UI with HTML CSS and js.
You can use bootstrap card codes from the internet.

**Comment by carlocardona** [comment]
What are the requirements for information, layout, you want to appear on the Profile page?

**Comment by chaitak-gorai** [comment]
> What are the requirements for information, layout, you want to appear on the Profile page?

It should contain 
 * Profile pic
 * Full name 
 * Followers and social media icons
 * About 
 *  template post( which will be used in backend to show his posts)

I am sharing some templates you can follow these 
https://bootsnipp.com/snippets/K0ZmK
https://www.bootdey.com/snippets/view/user-profile-bio-graph-and-total-sales

**Comment by chaitak-gorai** [comment]
This issue is soved by @chaitak-gorai by the commit 7a7af3ac7b29a5ceedac7e7a25468589d249a3f2
