### ISSUE TITLE
Add a favicon image

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/blogbook#19]
- The logo-like image visible in the tab of a browser is a favicon.
- To add a favicon covert the logo to ico format through online converters.
- add that image to the file directory
- add these codes to the head section

The best favicon icon for the site will be merged.

Thank you! Keep Contributing

**Comment by aviwar** [comment]
Hi, I want to work on this issue.

**Comment by chaitak-gorai** [comment]
Yes go ahead.

**Comment by aviwar** [comment]
@chaitak-gorai No logo available in folders. Are we going to pick new one and convert it.

**Comment by chaitak-gorai** [comment]
Yes.. You can choose any blog related favicons which suit the site..

**Comment by chaitak-gorai** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.freeiconspng.com%2Fimages%2Fbook-icon&psig=AOvVaw236zXMCsYaYb5kkqoGvowA&ust=1633429883160000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMCxydLGsPMCFQAAAAAdAAAAABAP

Use this type of favocon

**Comment by chaitak-gorai** [comment]
This issue is solved by the commit ee20878a86fd90bf04ec032e2cf4278e00c143aa and some minor changes after that.
Special thanks to @aviwar for their contibution.

**Comment by chaitak-gorai** [comment]
Still, we have to add the favicon to the admin section as it has another header file.

**Comment by aviwar** [comment]
@chaitak-gorai Favicon added for admin section.

**Comment by chaitak-gorai** [comment]
This issue is finally solved by the commit 28c6d29a42ceeb3b05d884859ab82d3e45be7e3f
Great work from @aviwar. Keep Contributing :)
