### ISSUE TITLE
Add "go to top"

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/blogbook#20]
Add go to top feature for index and posts pages.

Files to change
- index.php 
- posts.php

Thank you! Keep Contributing

**Comment by myli14** [comment]
I would like to work on this issue, if it's still up for grabs.

**Comment by chaitak-gorai** [comment]
Yes sure. You can go ahead. @myli14

**Comment by myli14** [comment]
I just want to make sure. 
1. Feature which we are thinking of is something like "Home" button on keyboard, which changes position of scroll or It has to do with something else?
2. Do you have any limitations? By that I mean, specific programming language? (For me personally, it would be easy thing to do in JS)

**Comment by chaitak-gorai** [comment]
> I just want to make sure.
> 
> 1. Feature which we are thinking of is something like "Home" button on keyboard, which changes position of scroll to 0,0 or It has to do with something else?
> 2. Do you have any limitations? By that I mean, specific programming language? (For me personally, it would be easy thing to do in JS)

This is not so complex. 
You can do:
- Add an "upper arrow icon" on the bottom right
- link that to any div on the top eg nav
- Add smooth-scrolling to body 

Also, you can use any language of your choice. Html CSS is sufficient for this job. 
Thank You

**Comment by myli14** [comment]
Should I make pull request to "main" or to "chaitak-gorai-patch-1" branch?

**Comment by chaitak-gorai** [comment]
You can commit to main.

**Comment by chaitak-gorai** [comment]
This issue is solved by commit 6fc8bfa8082423ab4ff2f985ee9ceac1ced060e3 and 40f77f2540a7c7056fc8c8ab4e2564150a6946ba 
Special thanks to @myli14 for the contribution. Kindly update contributors.md.
Thank you! Keep contributing :)
