### ISSUE TITLE
Remove text decoration of content of blog cards

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/blogbook#22]
When the blog card on the home page is hovered, the blog content summary gets underlined as it is a link.

Solve this issue.

Thank you! Keep Contributing

**Comment by ShubhamKrSingh21** [comment]
I want to work in this issue.

**Comment by chaitak-gorai** [comment]
yes @ShubhamKrSingh21 go ahead

**Comment by chaitak-gorai** [comment]
This issue is solved by the commit 7ab6839bf234fac817593fffc70617a620ff62e8 and dff4444f29fb5306a780f94ded83549b2aa90050. 
Special thanks to @ShubhamKrSingh21  and @pdejan for thier contributions.
Thank You! Keep Contributing :)
