### ISSUE TITLE
Show Views Count of posts

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/blogbook#24]
The views count of each post is shown in the admin section but at present, it is not shown in UI or Home page.

Write a PHP query and access the "post_views_count" from the "posts" table. And show that count in UI both in index page card and Post page too.

For any other help and question feel free to ask.
Thanks for contributing!

**Comment by kaiquegarcia** [comment]
Hey @chaitak-gorai! Can I pick this one too?

**Comment by chaitak-gorai** [comment]
Yes, go ahead. Do the necessary changes and create a PR.

**Comment by chaitak-gorai** [comment]
this issue is solved by the commits f75587b5508558d62664eec2f6a6b43d456003dc and 482ad96fd08bbf15c398fab077903f4d30228d52.
Special thanks to @kaiquegarcia for their contribution.

**Comment by chaitak-gorai** [comment]
I am not closing this issue for now. As there are some more places to make changes.
- categories.php
-  side widget top posts

This is open to all. Anyone can take this.

**Comment by chaitak-gorai** [comment]
This issue is closed.
