### ISSUE TITLE
Check for unique username in register

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/blogbook#27]
This is a major bug. There is no check at present if the username already exists or not.
This issue needs to be solved.
Check the "usename" row for "users" table in the register query. if it exists give an error message in the UI.

Files to check/update
-registration.php
-register_script.php

**Comment by aviwar** [comment]
Hi @chaitak-gorai, could you assign this issue to me.

**Comment by chaitak-gorai** [comment]
Hello, @aviwar I have assigned you this issue.
Try to make it in an asynchronous way ie without relaoding the register page.
All the best!

**Comment by chaitak-gorai** [comment]
This issue is solved by the commit 767b0595e5605a630025bf7e79faabf0dd9bd39b .
Thanks to @aviwar for his great contribution.
