### ISSUE TITLE
Change title to "Blogbook"

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/blogbook#4]
FIles to lookout
includes/header.php

**Comment by rmhassan** [comment]
I have opened a pull request. Updated title in header.php.

**Comment by chaitak-gorai** [comment]
This issue is solve by commit caf3349bfb15777e23f6ea0236b583a87c71df04.
Shout out to @rmhassan for his commit.
This is the first contribution to this project as open source.

**Comment by rmhassan** [comment]
@chaitak-gorai Thanks.
This was my first commit as well to an open-source project. Looking forward to many more.

**Comment by chaitak-gorai** [comment]
Good luck for your open source journey.

**Comment by chaitak-gorai** [comment]
Create contributors.md file and add your name to the list.
