### ISSUE TITLE
Modify The `Read More` Btn Design

### ISSUE THREAD

**Issue by shubhamjha25** [chaitak-gorai/blogbook#45]
While exploring the project, I found that the `READ MORE` Button on the Home page is too static.
It doesn't seems smooth to me, and also compatible if we compare it with the UI of the the entire application.

When we hover it, the `#ffb535` background pops up in entire one go. 
I would like to **modify** the btn design.
Add a smooth **transition** for the `#ffb535` background to complete the btn-width.
 
Can we make it like this? 👇🏻

![ReadMoreBtnGif](https://user-images.githubusercontent.com/63443481/135915339-5a779f73-e928-4f9a-9e45-20b4bb73d69a.gif)

This seems good and can **enhance** the overall UI of the application.
Would like to work on it if you like the idea and **assign** me to this issue.
Thanks! 😀

**Comment by chaitak-gorai** [comment]
Hello, @shubhamjha25 this is a great observation. 
Go ahead with the issue, do the necessary changes and create a PR. 
Thank you!
