### ISSUE TITLE
No `Code of Conduct` Documentation

### ISSUE THREAD

**Issue by shubhamjha25** [chaitak-gorai/blogbook#52]
A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions. It also outlines procedures for addressing problems between members of your project's community.

Ideally, the code of conduct should be created at the time of project creation.
Still, I wish to create the documentation for the same.
I'll place a **CODE_OF_CONDUCT** file in the project’s root directory, and make it visible to the community by linking it from your CONTRIBUTING or README file.

If you want, then do assign me to this issue.
Thanks! 😄

**Comment by chaitak-gorai** [comment]
Yes, this is something our project is missing right now. 
Please go ahead and add the CODE_OF_CONDUCT .
Thanks for the suggestion and contribution.

**Comment by chaitak-gorai** [comment]
This is issue is solved by the commit 586e4104c62e112f12b96f732d8cd4f6f31c007e.
Special thanks to @shubhamjha25  for identifying as well as solving the use.
Keep Contributing.
