### ISSUE TITLE
Show user profile page in "Profile" 

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/blogbook#55]
At present  "profile" section contains the "update profile" part. 
 we have a profile page for each user at URL  /users.php?u_id=$user_id. So we can include that in the profile section.
 
After update, the profile section should contain
- Update profile-
- View Profile 

Files to check/update
- ad_navigation.php
- profile.php

**Comment by chaitak-gorai** [comment]
> Hey, can I pick this one too? I have a few questions...
> 
> 1. Is that URL the right path? I think it's `/user.php?u_id=$user_id` 

> 2. Is the issue about adding a new "button" in the end of the "Update profile" form?instead of `/users(...)` (single user, not plural)

Yes, there is a slight mistake..it is "user" not "users"
It should be like a dropdown. One option will be "update profile". other will be "view public profile"
![asdf](https://user-images.githubusercontent.com/77141674/136134000-dcccd8b0-86ba-43bd-8ae5-4f94057c44fe.PNG)

**Comment by kaiquegarcia** [comment]
Ok! Now I got it. You came just in time hahah

**Comment by chaitak-gorai** [comment]
This issue is solved.
Great contribution from @kaiquegarcia .
Thank you.
