### ISSUE TITLE
Comments Query failed

### ISSUE THREAD

**Issue by chaitak-gorai** [chaitak-gorai/blogbook#68]
If we use any quotes, colons,etc in our comments  the comment query failed .

Files to change:
- post.php

Hint: use real_escape string for content

**Comment by akshaygidwani404** [comment]
Hi @chaitak-gorai Can you assign this task to me?

**Comment by mmedery** [comment]
Hello,
@chaitak-gorai, I'm working on it, at the latest tomorrow it will be ready
Thank you for your understanding

**Comment by chaitak-gorai** [comment]
Ok no issue

**Comment by mmedery** [comment]
@chaitak-gorai ,
Can I ask for more information about the problem, because when I typed ": it showed up in the comments.

**Comment by chaitak-gorai** [comment]
@mmedery 
try using quotes ie '' ''  it will give a query error.
